language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

# Make sure we have GCC with C++11 support.
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq; fi
install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq g++-5.3 && export CXX="g++-5.3" && export CC="gcc-5.3"; fi

script:
  - make -C tests

